import{g as I,m as d,a as L,b as P,c as B,d as N}from"./assets/applebooks@2x-32274212.js";const w="https://books-backend.p.goit.global/books",z={list:"category-list",top:"top-books",category:"category?category="};async function R(e,t=""){try{return await(await fetch(`${w}/${e}${t}`)).json()}catch{alert("An error occurred")}}async function j(e){try{return await(await fetch(`${w}/${e}`)).json()}catch{alert("An error occurred")}}const s={API_OPTIONS:z,fetchBookList:R,fetchBookById:j},D=document.querySelector(".ctg-list");s.fetchBookList(s.API_OPTIONS.list).then(e=>{const t=e.map(({list_name:o})=>`<li class="ctg-item js-ctg-item " data-ctg-name = ${o}>${o}
          </li>`).join("");D.insertAdjacentHTML("beforeend",t)});const i=I();s.fetchBookList(s.API_OPTIONS.top).then(d.renderTopBooks);function v(e){[...i.ctgList.children].forEach(t=>t.classList.remove("ctg-item-active")),i.ctgList.contains(e.target)?e.target.classList.add("ctg-item-active"):[...i.ctgList.children].find(o=>o.textContent.trim()===e.target.dataset.category).classList.add("ctg-item-active")}function H(e){const t=e.target.childNodes[0].data;v(e),t!=="All categories"?s.fetchBookList(s.API_OPTIONS.category,t).then(d.renderCategoryBooks):s.fetchBookList(s.API_OPTIONS.top).then(d.renderTopBooks)}function q(e){if(!e.target.classList.contains("top-books-button"))return;const t=e.target.dataset.category;v(e),s.fetchBookList(s.API_OPTIONS.category,t).then(d.renderCategoryBooks)}i.ctgList.addEventListener("click",H);i.bookCollectionWrapper.addEventListener("click",q);const F=I(),g=document.getElementById("bookModal"),u=document.getElementById("bookModalTitle"),J=document.getElementById("bookModalBody"),a=document.getElementById("addToShoppingList"),U=document.querySelector(".modal-close"),p=document.getElementById("modalFooterText");let n=[],l=[],T={};const W="The Duke of Sussex details his struggles with the royal family, loss of his mother, service in the British Army and marriage to Meghan Markle. Read by the author. 15 hours, 39 minutes unabridged.";function Y(e){s.fetchBookById(e).then(t=>{u.innerText=t.title,t.description||(t.description=W),T={book_image:t.book_image,title:t.title,author:t.author,description:t.description,amazonLinks:t.buy_links[0].url,appleLinks:t.buy_links[1].url},u.dataset.bookId=e,J.innerHTML=`<img src="${t.book_image}" alt="${t.title}" class="book-modal-img"/>
            <div class="book-modal-details">
                <h2 class="book-modal-title">${t.title}</h2>
                <h3 class="book-modal-author">${t.author}</h3>
                <p class="book-modal-desc">${t.description}</p>
                <ul class="icon-book-modal-list">
                    <li>
                        <a href="${t.buy_links[0].url}" rel="noopener noreferrer nofollow" target="_blank">
                            <img class="icon-book-modal-amazon" srcset="${L} 1x, ${P} 2x" src="${L}" alt="Amazon" loading="lazy"/>
                        </a>
                    </li>
                    <li>
                        <a href="${t.buy_links[1].url}" rel="noopener noreferrer nofollow" target="_blank">
                            <img class="icon-book-modal-ibooks" srcset="${B} 1x, ${N} 2x" src="${B}" alt="Apple books" loading="lazy"/>
                        </a>
                    </li>
                </ul>
            </div>
    `,n.includes(e)?(a.innerText="Remove from the shopping list",p.style.display="block"):(a.innerText="Add to shopping list",p.style.display="none"),g.classList.add("show"),document.body.style.overflow="hidden"})}function h(){g.classList.remove("show"),document.body.style.overflow=""}function G(e){if(!e){console.error("Invalid bookId:",e);return}const t=n.indexOf(e);t===-1?(n.push(e),l.push(T)):(n.splice(t,1),l.splice(t,1)),localStorage.setItem("shoppingList",JSON.stringify(n)),localStorage.setItem("shoppingCard",JSON.stringify(l)),t===-1?(a.innerText="Remove from the shopping list",p.style.display="block"):(a.innerText="Add to shopping list",p.style.display="none")}a.addEventListener("click",()=>{const e=u.dataset.bookId;G(e)});g.addEventListener("click",e=>{e.target===g&&h()});document.addEventListener("keydown",e=>{e.key==="Escape"&&h()});F.bookCollectionWrapper.addEventListener("click",e=>{const t=e.target.closest(".book-link");if(t){e.preventDefault();const o=t.dataset.id;Y(o)}});const b=localStorage.getItem("shoppingList"),E=localStorage.getItem("shoppingCard");b&&(n=JSON.parse(b));E&&(l=JSON.parse(E));U.addEventListener("click",h);document.addEventListener("DOMContentLoaded",function(){document.getElementById("signupBtn").addEventListener("click",o);const t=document.createElement("div");t.style.position="fixed",t.style.top="20px",t.style.right="20px",t.style.background="red",t.style.color="white",t.style.padding="15px",t.style.display="none",t.style.zIndex="1",document.body.appendChild(t);async function o(){try{const x=await(await fetch("../partials/registration.html")).text(),C=document.getElementById("registrationModalContainer");C.innerHTML=x;const M=document.getElementById("registrationForm"),$=document.querySelector(".close-icon");M.addEventListener("submit",async function(O){O.preventDefault();const A=document.getElementById("name").value,f=document.getElementById("email").value,_=document.getElementById("password").value;try{const c=await firebase.auth().createUserWithEmailAndPassword(f,_),k={name:A,email:f,uid:c.user.uid};await firebase.firestore().collection("users").doc(c.user.uid).set(k),console.log("User data:",k),m()}catch(c){t.textContent=`Error creating user: ${c.message}`,t.style.display="block",setTimeout(function(){t.style.display="none"},1e4)}}),$.addEventListener("click",function(){t.style.display="none",m()})}catch(r){console.error("Error loading registration content:",r)}}function m(){const r=document.getElementById("registrationModalContainer");r.innerHTML=""}});const y=document.querySelector(".back-to-top");window.addEventListener("scroll",K);y.addEventListener("click",S);function K(){const e=window.pageYOffset,t=document.documentElement.clientHeight;e>t?y.classList.add("back-to-top--show"):y.classList.remove("back-to-top--show")}function S(){window.pageYOffset>0&&(window.scrollBy(0,-25),setTimeout(S,0))}
//# sourceMappingURL=commonHelpers.js.map
